import type { Translate } from "@/app/portal/lib/preferences-context";

export const MATCH_RESUME_PROMPT =
  "请依据 Candidate、Resume、目标 Job Requisition 与 JD 执行简历匹配前规则检查。目标客户和部门只能从目标岗位结构化证据解析，简历中的历史客户经历不得改变规则作用域。通过 SCOPED_TO、GOVERNS、APPLIES_TO、RELEVANT_TO 语义 Links 纳入 CSI 通用、目标客户通用及目标客户部门规则，并排除其他客户和部门；规范 Action 必须通过 GOVERNS/RELEVANT_TO 构成能力语义门。对每条规则给出可核验 evidence path，mandatory 决定阻断，optional 未满足仅 flag。";

export const MATCH_RESUME_EXAMPLE_DATA = {
  candidate: {
    candidate_id: "Candidate-RSN-IEG-001",
    name: "林澈（合成测试数据）",
    nationality: "中国",
    gender: "男",
    birth_date: "1992-08-17",
    phone: "138****4821",
    email: "lin.che@example.test",
    highest_acquired_degree: "本科",
    unified_enrollment: true,
    work_years: 7.8,
    status: "积极求职",
    state: "RESUME_PROCESSED",
    is_locked: false,
    blacklist_status: false,
    conflict_of_interest_declaration: "无已知利益冲突",
    current_city: "深圳",
    expected_salary_range: "22-26K",
    available_date: "2026-07-25",
    data_consent: {
      resume_processing: true,
      client_submission: true,
      captured_at: "2026-07-12T10:25:00+08:00",
    },
  },
  resume: {
    resume_id: "Resume-RSN-IEG-001",
    candidate_id: "Candidate-RSN-IEG-001",
    job_requisition_id: ["JobReq-R2026022729329"],
    parsing_status: "completed",
    is_original: true,
    updated_time: "2026-07-12T10:30:00+08:00",
    summary:
      "7年以上前端开发经验，4年游戏项目经验；熟悉 React、TypeScript、Node.js、Redux、Webpack 和前端性能优化。",
    skills: [
      "React",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Redux",
      "Webpack",
      "HTML5",
      "CSS3",
      "Jest",
      "Git",
    ],
    languages: "中文母语；英文技术文档熟练",
    education: [
      {
        school: "华南理工大学",
        major: "计算机科学与技术",
        degree: "本科",
        enrollment_type: "全日制统招",
        start_date: "2014-09-01",
        end_date: "2018-06-30",
        verification_status: "verified_for_demo",
      },
    ],
    employment_history: [
      {
        company: "荣耀终端有限公司",
        employment_type: "正式员工",
        title: "高级前端工程师",
        start_date: "2024-04-01",
        end_date: "2026-06-20",
        departure_type: "主动离职",
        responsibilities: [
          "负责运营后台 React/TypeScript 架构",
          "建立性能监控并将首屏耗时降低35%",
        ],
      },
      {
        company: "中软国际科技服务有限公司",
        employment_type: "外包员工",
        client_name: "腾讯",
        client_department_name: "IEG",
        studio: "天美工作室",
        title: "游戏前端工程师",
        start_date: "2020-03-01",
        end_date: "2024-03-15",
        departure_type: "项目正常结束",
        responsibilities: [
          "负责游戏内活动 UI 与运营平台",
          "使用 React、Redux、TypeScript、Node.js 和 Webpack",
        ],
      },
      {
        company: "小米科技有限责任公司",
        employment_type: "正式员工",
        title: "前端工程师",
        start_date: "2018-07-01",
        end_date: "2020-02-01",
        departure_type: "主动离职",
        responsibilities: ["负责管理后台和组件库"],
      },
    ],
    projects: [
      {
        name: "游戏活动运营平台",
        role: "核心前端",
        period: "2022-01~2024-03",
        stack: ["React", "TypeScript", "Node.js", "Webpack"],
        results: ["支撑20+活动并发配置", "通过分包与缓存将加载耗时降低40%"],
      },
      {
        name: "前端质量与性能体系",
        role: "负责人",
        period: "2024-06~2026-05",
        stack: ["Jest", "Playwright", "Web Vitals"],
        results: ["覆盖率提升到82%", "线上前端错误率下降45%"],
      },
    ],
    raw_text:
      "林澈｜男｜1992年8月｜深圳｜本科｜7年以上前端开发经验\n求职方向：InGame前端开发；期望城市：深圳；期望薪资：22-26K；可到岗日期：2026-07-25。\n教育经历：2014-09至2018-06，华南理工大学，计算机科学与技术，全日制统招本科。\n工作经历一：2024-04至2026-06-20，荣耀终端有限公司，正式员工，高级前端工程师。负责运营后台React/TypeScript架构，建设前端性能监控体系，将首屏耗时降低35%。离职类型：主动离职。\n工作经历二：2020-03至2024-03-15，中软国际科技服务有限公司，外包员工，派驻腾讯IEG天美工作室，游戏前端工程师。负责游戏内活动UI与运营平台，使用React、Redux、TypeScript、Node.js和Webpack；项目正常结束离场。\n工作经历三：2018-07至2020-02-01，小米科技有限责任公司，正式员工，前端工程师。负责管理后台与组件库；主动离职。\n项目一：游戏活动运营平台（2022-01至2024-03），核心前端，React/TypeScript/Node.js/Webpack，支撑20多个活动并发配置，通过分包与缓存将加载耗时降低40%。\n项目二：前端质量与性能体系（2024-06至2026-05），负责人，Jest/Playwright/Web Vitals，单测覆盖率提升至82%，线上前端错误率下降45%。\n技能：React、TypeScript、JavaScript、Node.js、Redux、Webpack、HTML5、CSS3、Jest、Git。语言：中文母语，可熟练阅读英文技术文档。",
  },
  jobRequisition: {
    job_requisition_id: "JobReq-R2026022729329",
    job_requisition_specification_id: "JobReqSpec-Tencent-IEG-2026-001",
    client_id: "Client-Tencent-001",
    client_name: "腾讯",
    client_department_id: "ClientDepartment-Tencent-IEG-001",
    client_department_name: "IEG",
    client_studio: "光子工作室",
    csi_department_id: "CSIDepartment-RaaS-Delivery-001",
    csi_department_name: "RAAS交付管理部",
    client_job_id: "R2026022729329",
    client_job_title: "InGame前端开发",
    client_job_type: "前端开发（游戏）",
    job_type: "前端开发（游戏）",
    recruitment_type: "外包",
    work_years: 3,
    degree_requirement: "本科",
    education_requirement: "全日制本科及以上",
    city: "深圳",
    work_address: ["深圳腾讯滨海大厦"],
    salary_range: "18-28K",
    must_have_skills: ["React", "TypeScript", "JavaScript", "Node.js", "Redux"],
    nice_to_have_skills: ["游戏内UI经验", "Webpack工程化", "前端性能优化"],
    language_requirements: "能阅读英文技术文档",
    negative_requirement:
      "不接受缺少React/TypeScript实战、无法说明性能优化经验的候选人",
    headcount: 1,
    hc_status: "open",
    urgency_level: "高",
    open_date: "2026-07-01",
    required_arrival_date: "2026-08-01",
    work_schedule_type: "标准工作制",
    require_foreigner: false,
    interview_mode: "内部技术面 + 腾讯 IEG 客户复面",
    expected_level: "L3-L4",
  },
  jd: {
    jd_id: "JD-RSN-IEG-001",
    title: "腾讯 IEG InGame 前端开发（外包）",
    client: "腾讯",
    business_group: "IEG",
    studio: "光子工作室",
    responsibilities: [
      "负责游戏内活动与运营系统前端研发",
      "负责React/TypeScript工程架构、质量与性能优化",
      "与策划、后端、测试协作交付",
    ],
    mandatory_requirements: [
      "全日制本科及以上",
      "3年以上前端经验",
      "熟练React、TypeScript、JavaScript、Redux、Node.js",
      "具备独立模块设计和性能优化能力",
    ],
    optional_requirements: [
      "游戏内UI经验",
      "Webpack工程化经验",
      "自动化测试经验",
    ],
    disqualifiers: [
      "学历不满足",
      "无React/TypeScript项目证据",
      "存在适用客户/部门合规红线且未解除",
    ],
    employment_type: "外包",
    location: "深圳",
    salary_range: "18-28K",
  },
  genericInputs: {
    evaluation_context: {
      as_of_date: "2026-07-14",
      timezone: "Asia/Shanghai",
      purpose: "pre_match_rule_check",
    },
    rule_scope: {
      capability_anchors: ["ruleCheckForMatchResume", "matchResume"],
      target_scope_source: "job_requisition_and_jd",
      csi_policy: "include_universal",
      include_client_wide_rules: true,
      include_department_rules: true,
      exclude_other_clients: true,
      exclude_other_departments: true,
    },
    csi_department: {
      csi_department_id: "CSIDepartment-RaaS-Delivery-001",
      dept_name: "RAAS交付管理部",
      specific_hiring_rules: "推荐前必须完成简历一致性、技能深度与稳定性检查",
      red_line_policy: "不得提交资料缺失、黑名单命中或适用红线未解除的候选人",
    },
    application_history: [],
    blacklist_records: [],
    compliance_documents: [],
    active_locks: [],
    interview_history: [],
  },
} as const;

export const BYTEDANCE_MATCH_RESUME_PROMPT =
  "请依据 Candidate、Resume、目标 Job Requisition 与 JD 执行简历匹配前规则检查。目标客户和部门只能从目标岗位结构化证据解析，不能从用户文字或简历历史派驻客户推断。只通过语义 Links 纳入 CSI 通用、目标客户通用及目标客户部门规则并排除其他客户和部门；规范 Action 必须通过 GOVERNS/RELEVANT_TO 构成能力语义门。逐条返回 evidence path，并按 mandatory/optional 执行确定性裁决。";

export const BYTEDANCE_MATCH_RESUME_EXAMPLE_DATA = {
  candidate: {
    candidate_id: "Candidate-RSN-BD-001",
    name: "周知遥（合成测试数据）",
    nationality: "中国",
    gender: "女",
    birth_date: "1993-11-08",
    phone: "139****7612",
    email: "zhou.zhiyao@example.test",
    highest_acquired_degree: "本科",
    unified_enrollment: true,
    work_years: 8,
    status: "积极求职",
    state: "RESUME_PROCESSED",
    is_locked: false,
    blacklist_status: false,
    conflict_of_interest_declaration: "已披露历史客户与供应商经历",
    current_city: "北京",
    expected_salary_range: "28-34K",
    available_date: "2026-07-28",
    data_consent: {
      resume_processing: true,
      client_submission: true,
      captured_at: "2026-07-13T09:20:00+08:00",
    },
  },
  resume: {
    resume_id: "Resume-RSN-BD-001",
    candidate_id: "Candidate-RSN-BD-001",
    job_requisition_id: ["JobReq-BD-Ecom-2026-017"],
    parsing_status: "completed",
    is_original: true,
    updated_time: "2026-07-13T09:30:00+08:00",
    summary:
      "8年前端与数据产品研发经验，熟悉 React、TypeScript、Node.js、微前端和大规模运营平台；具有互联网客户正编及供应商派驻经历。",
    skills: [
      "React",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Micro Frontends",
      "Webpack",
      "Jest",
      "Playwright",
      "Data Visualization",
      "Git",
    ],
    languages: "中文母语；英文技术沟通熟练",
    education: [
      {
        school: "北京邮电大学",
        major: "软件工程",
        degree: "本科",
        enrollment_type: "全日制统招",
        start_date: "2014-09-01",
        end_date: "2018-06-30",
        verification_status: "verified_for_demo",
      },
    ],
    employment_history: [
      {
        company: "博彦科技股份有限公司",
        employment_type: "外包员工",
        client_name: "字节",
        client_department_name: "抖音电商",
        business_type: "非BPO研发外包",
        title: "资深前端工程师",
        start_date: "2024-01-08",
        end_date: "2026-05-20",
        departure_type: "项目结束",
        responsibilities: [
          "派驻客户电商业务，负责商家运营平台和数据看板",
          "负责React/TypeScript微前端架构与性能治理",
        ],
      },
      {
        company: "字节跳动有限公司",
        employment_type: "正式员工",
        client_name: "字节",
        client_department_name: "抖音电商",
        title: "前端开发工程师",
        start_date: "2021-02-01",
        end_date: "2023-12-15",
        departure_type: "主动离职",
        responsibilities: ["负责营销活动搭建平台", "建设前端监控与质量体系"],
      },
      {
        company: "小米科技有限责任公司",
        employment_type: "正式员工",
        title: "前端工程师",
        start_date: "2018-07-02",
        end_date: "2021-01-15",
        departure_type: "主动离职",
        responsibilities: ["负责IoT运营后台和组件库"],
      },
      {
        company: "中软国际科技服务有限公司",
        employment_type: "外包员工",
        client_name: "腾讯",
        client_department_name: "IEG",
        studio: "光子工作室",
        title: "短期项目顾问",
        start_date: "2018-03-01",
        end_date: "2018-06-15",
        departure_type: "实习项目结束",
        responsibilities: ["参与游戏活动页面开发"],
      },
    ],
    projects: [
      {
        name: "电商商家运营平台",
        role: "前端负责人",
        period: "2024-01~2026-05",
        stack: ["React", "TypeScript", "Node.js", "Micro Frontends"],
        results: ["支撑万级商家日常运营", "首屏耗时下降38%"],
      },
      {
        name: "营销活动搭建平台",
        role: "核心开发",
        period: "2021-08~2023-12",
        stack: ["React", "Webpack", "Data Visualization"],
        results: ["活动交付周期缩短45%", "线上错误率下降40%"],
      },
    ],
    raw_text:
      "周知遥｜女｜1993年11月｜北京｜全日制本科｜8年前端开发经验。\n求职方向：电商运营平台前端；期望薪资28-34K；2026-07-28可到岗。\n教育：2014-09至2018-06，北京邮电大学软件工程全日制本科。\n经历一：2024-01-08至2026-05-20，博彦科技股份有限公司，非BPO研发外包，派驻字节抖音电商，资深前端工程师，负责商家运营平台、数据看板与微前端性能治理；项目结束离场。\n经历二：2021-02-01至2023-12-15，字节跳动有限公司正式员工，抖音电商前端开发工程师，负责营销活动搭建平台和质量体系；主动离职。\n经历三：2018-07-02至2021-01-15，小米科技有限责任公司正式员工，负责IoT运营后台和组件库；主动离职。\n经历四：2018-03-01至2018-06-15，中软国际外包实习项目，历史派驻腾讯IEG光子工作室。该历史客户不是本次目标岗位客户。\n技能：React、TypeScript、JavaScript、Node.js、微前端、Webpack、Jest、Playwright、数据可视化。",
  },
  jobRequisition: {
    job_requisition_id: "JobReq-BD-Ecom-2026-017",
    job_requisition_specification_id: "JobReqSpec-BD-Ecom-2026-017",
    client_id: "Client-ByteDance-001",
    client_name: "字节",
    client_legal_name: "北京字节跳动科技有限公司",
    client_department_id: "ClientDepartment-BD-Ecom-001",
    client_department_name: "抖音电商",
    csi_department_id: "CSIDepartment-RaaS-Delivery-001",
    csi_department_name: "RAAS交付管理部",
    client_job_id: "BD-Ecom-FE-2026-017",
    client_job_title: "电商运营平台资深前端开发",
    client_job_type: "前端开发（电商）",
    recruitment_type: "外包",
    work_years: 5,
    degree_requirement: "本科",
    education_requirement: "全日制本科及以上",
    city: "北京",
    work_address: ["北京海淀区客户办公区"],
    salary_range: "25-35K",
    must_have_skills: ["React", "TypeScript", "Node.js", "微前端", "性能优化"],
    nice_to_have_skills: ["电商平台经验", "数据可视化", "自动化测试"],
    language_requirements: "可进行英文技术沟通",
    negative_requirement: "不接受无法说明大型平台性能治理案例的候选人",
    headcount: 2,
    hc_status: "open",
    urgency_level: "高",
    open_date: "2026-07-01",
    required_arrival_date: "2026-08-10",
    work_schedule_type: "标准工作制",
    interview_mode: "内部技术面 + 客户业务面",
    expected_level: "资深",
  },
  jd: {
    jd_id: "JD-RSN-BD-Ecom-001",
    title: "电商运营平台资深前端开发（外包）",
    client: "字节",
    business_group: "抖音电商",
    responsibilities: [
      "负责商家运营平台前端架构与核心模块研发",
      "负责微前端治理、工程质量与性能优化",
      "与产品、后端、测试协作完成业务交付",
    ],
    mandatory_requirements: [
      "全日制本科及以上",
      "5年以上前端经验",
      "熟练React、TypeScript、Node.js",
      "具有复杂平台架构与性能治理经验",
    ],
    optional_requirements: ["电商业务经验", "数据可视化", "自动化测试"],
    disqualifiers: [
      "学历不满足",
      "缺少核心技术项目证据",
      "存在未解除的客户回流或岗位冷冻期红线",
    ],
    employment_type: "外包",
    location: "北京",
    salary_range: "25-35K",
  },
  genericInputs: {
    evaluation_context: {
      as_of_date: "2026-07-14",
      timezone: "Asia/Shanghai",
      purpose: "pre_match_rule_check",
    },
    rule_scope: {
      capability_anchors: ["ruleCheckForMatchResume", "matchResume"],
      target_scope_source: "job_requisition_and_jd",
      csi_policy: "include_universal",
      include_client_wide_rules: true,
      include_department_rules: true,
      exclude_other_clients: true,
      exclude_other_departments: true,
    },
    csi_department: {
      csi_department_id: "CSIDepartment-RaaS-Delivery-001",
      dept_name: "RAAS交付管理部",
      specific_hiring_rules: "推荐前完成简历一致性、历史客户经历与稳定性检查",
    },
    application_history: [
      {
        application_id: "Application-BD-20260625-001",
        job_requisition_id: "JobReq-BD-Ecom-2026-017",
        client_name: "字节",
        result: "面试淘汰",
        result_date: "2026-06-25",
      },
    ],
    compliance_documents: [
      {
        document_id: "Compliance-BD-Return-001",
        document_type: "字节正编回流客户BP确认凭证",
        verification_status: "有效",
        issued_at: "2026-07-08",
        conclusion: "无异常且可回流",
      },
    ],
    blacklist_records: [],
    active_locks: [],
    interview_history: [],
  },
} as const;

function serializeExample(data: {
  candidate: unknown;
  resume: unknown;
  jobRequisition: unknown;
  jd: unknown;
  genericInputs: unknown;
}) {
  return {
    candidate: JSON.stringify(data.candidate, null, 2),
    resume: JSON.stringify(data.resume, null, 2),
    jobRequisition: JSON.stringify(data.jobRequisition, null, 2),
    jd: JSON.stringify(data.jd, null, 2),
    genericInputs: JSON.stringify(data.genericInputs, null, 2),
  };
}

export const MATCH_RESUME_EXAMPLE = serializeExample(MATCH_RESUME_EXAMPLE_DATA);
export const BYTEDANCE_MATCH_RESUME_EXAMPLE = serializeExample(
  BYTEDANCE_MATCH_RESUME_EXAMPLE_DATA,
);

export function getReasoningTestExamples(t: Translate) {
  return [
    {
      id: "tencent-ieg",
      label: t("reasoningAgent.examples.tencentIeg.label"),
      prompt: MATCH_RESUME_PROMPT,
      context: MATCH_RESUME_EXAMPLE,
    },
    {
      id: "bytedance-ecommerce",
      label: t("reasoningAgent.examples.bytedanceEcommerce.label"),
      prompt: BYTEDANCE_MATCH_RESUME_PROMPT,
      context: BYTEDANCE_MATCH_RESUME_EXAMPLE,
    },
  ] as const;
}
