/**
 * Boot-time wiring: runs `bootstrapAll()` from @agentic/runtime which reads
 * manifests from `models/<slug>/` and returns an array of Inngest functions,
 * then exposes them via the `inngest/fastify` adapter.
 *
 * Tenant code wiring lives HERE (not in @agentic/runtime) because pnpm's
 * isolated module resolution requires each package to declare its own deps.
 * To add a new tenant with custom tools/prompts:
 *   1. Create `tenants/<slug>/` (see tenants/raas/ as the template)
 *   2. Add `"@tenants/<slug>": "workspace:*"` to apps/api/package.json
 *   3. Import + register here
 *   4. Drop `models/<slug>/` for the manifest
 *
 * Pure-declarative tenants (manifest only, no custom code) skip steps 1-3
 * and just need a `models/<slug>/` folder — bootstrap auto-discovers them
 * and they run with the generic @agentic/tools fallbacks.
 */

import {
  bootstrapAll,
  helloFn,
  inngest,
  setRuntimeGateway,
  setRuntimeMetrics,
  type TenantRegistries,
} from "@agentic/runtime";
import type { Inngest, InngestFunction } from "inngest";
import raasTenant from "@tenants/raas";
import systemTenant from "@tenants/__system";
import tenantTest1 from "@tenants/tenant-test1";
import robohireTenant from "@tenants/robohire";
import northwindTenant from "@tenants/northwind";
import insightlabTenant from "@tenants/insightlab";
import {
  bootstrapCodeAgents,
  setGateway as setAgentGateway,
} from "@agentic/agents";
import "@agentic/agents/system";
import type { TenantRegistry } from "@agentic/agent-kit";
import { getMcpManager, type McpServerConfig } from "@agentic/mcp";
import { buildSkillTools, type SkillDescriptor } from "@agentic/skills";
import { getLLMGateway } from "./services/llm";
import { metrics } from "./services/metrics";
import { reconcileImports } from "./services/reconcile-imports";
import { getDb, pruneRolledBackDeployments } from "@agentic/db";
import {
  initInngestRegistry,
  reregisterInngest,
} from "./services/inngest-registry";
import {
  applyDemoModeOverrides,
  describeDemoMode,
  describeDemoOverrides,
  isDemoMode,
} from "./config/demo-mode.js";
import { startDemoRunner } from "./services/demo-runner.js";
import { runSeedRich } from "../scripts/seed-rich.js";

/**
 * v4 typing: TS2742 surfaces because `InngestFunction` references internal
 * `api/api` symbols. Pin the return type so consumers don't need to import
 * package internals.
 */
export interface BootstrapResult {
  inngest: Inngest.Any;
  functions: InngestFunction.Any[];
  /**
   * `stop()` for the demo-runner interval timers. No-op when
   * `AGENTIC_DEMO_MODE` is false (production) or `NODE_ENV=test`. The
   * server.ts entrypoint wires this into the graceful-shutdown drain so
   * SIGTERM cleanly clears the timers before `process.exit`.
   */
  stopDemoRunner: () => void;
}

/**
 * Map of tenant slug → tenant code registry. Keys MUST match the slug
 * derived from each `models/<folder>/` directory (e.g. "RAAS-v1" → "raas").
 *
 * Wave 4 made `definePrompt` required at boot per
 * `docs/tech-design/ar-tool.md` Option B. `__system` ships the two stub
 * prompts (`checkShape` + `applyRules`) shared by every platform
 * test-fixture workflow; without this the tests (`AGENTIC_DEV_TENANT=__system`)
 * can't boot the api.
 *
 * Stale `mi*` model directories on disk (auto-generated by the
 * manifest-import e2e suite) fail at the "tenant not seeded" check inside
 * `bootstrapTenant`, NOT at the prompt check — so they don't need an entry
 * here. `bootstrapAll`'s per-tenant try/catch keeps them from blocking boot.
 */
const TENANT_REGISTRIES: TenantRegistries = {
  raas: raasTenant,
  __system: systemTenant,
  "tenant-test1": tenantTest1,
  robohire: robohireTenant,
  northwind: northwindTenant,
  insightlab: insightlabTenant,
};

/**
 * MCP/Skills-expanded registries are cached after boot so manifest deploys
 * can rebuild the live Inngest function set without reconnecting external
 * servers or losing tenant prompt/tool overrides.
 */
let cachedExpanded: TenantRegistries = {};

export async function rebuildTenantFns(): Promise<InngestFunction.Any[]> {
  return bootstrapAll(cachedExpanded);
}

/** Code-defined agents are synchronously invoked in v1 and add no functions. */
export async function rebuildCodeAgentFns(): Promise<InngestFunction.Any[]> {
  await bootstrapCodeAgents();
  return [];
}

export async function bootstrapRuntime(): Promise<BootstrapResult> {
  // 0. Surface the demo-mode flag at the very top of the boot log so the
  //    operator can tell at a glance which mode the api is running in
  //    (production = no mock, demo = seed + loop). The architectural rule
  //    is locked: a single flag controls all "synthetic-data" behavior.
  console.log(describeDemoMode());

  // 0a. Apply demo-mode env overrides BEFORE the LLM gateway is constructed.
  //     When demo mode is ON, this swaps LLM_DEFAULT_PROVIDER → "mock" (and
  //     model → "mock-model-v1") so the demo runner's 30-sec-tick traffic
  //     never bills real LLM APIs. The on-disk `.env` is NOT touched —
  //     flipping AGENTIC_DEMO_MODE=false on the next restart restores the
  //     original values automatically. Operators can opt back into a real
  //     provider under demo mode via AGENTIC_DEMO_LLM_PROVIDER /
  //     AGENTIC_DEMO_LLM_MODEL escape hatches.
  const overrides = applyDemoModeOverrides();
  if (overrides.length > 0) {
    console.log(describeDemoOverrides(overrides));
  }

  // 1. Construct LLM gateway once and wire it into both consumers
  //    (agents package for BaseAgent.run, runtime package for step-engine logic actions).
  const gateway = getLLMGateway();
  setAgentGateway(gateway);
  setRuntimeGateway(gateway);
  // UC-V11-22 / AR-GAP-07 — wire the prometheus metrics registry into
  // the manifest engine. Without this the registry exists but
  // `runs_total`, `run_duration_ms` stay flat for any traffic the
  // manifest engine handles (i.e. all RAAS runs).
  setRuntimeMetrics(metrics);
  console.log(
    `[bootstrap] LLM gateway online — default provider=${gateway.defaultProvider}, default model=${gateway.defaultModel ?? "(adapter default)"}, ${gateway.listProviders().length} providers registered`,
  );

  // 2. Bootstrap code-defined agents (writes agents/agent_versions/deployments rows).
  const codeSummary = await bootstrapCodeAgents();
  console.log(
    `[bootstrap] code agents ready — ${codeSummary.agentCount} registered, ${codeSummary.deploymentsWritten} new deployment(s)`,
  );

  // 3. Expand each tenant registry with MCP-bridged tools + Skills tools
  //    BEFORE handing the map to `bootstrapAll`. This keeps `@agentic/runtime`
  //    blissfully unaware of MCP/Skills — the runtime sees a single
  //    `tenantRegistry.tools` map and dispatches as usual.
  const expanded: TenantRegistries = {};
  for (const [slug, base] of Object.entries(TENANT_REGISTRIES)) {
    expanded[slug] = await expandTenantRegistry(slug, base);
  }
  cachedExpanded = expanded;

  // 4. Manifest-driven (RAAS etc) Inngest functions.
  const tenantFns = await bootstrapAll(expanded);
  const allFns = [helloFn, ...tenantFns];
  initInngestRegistry({
    client: inngest as Inngest.Any,
    base: [helloFn],
    codeAgent: [],
    tenant: tenantFns,
  });
  console.log(
    `[bootstrap] api serving ${allFns.length} Inngest function(s) (${tenantFns.length} from tenant manifests)`,
  );

  // 4. Crash recovery for the manifest-import wizard (per review C1).
  //    `reconcileImports` does three things:
  //      a. Drop expired `status='pending'` rows + their staging dirs.
  //      b. Complete crashed renames: rows where `file_path` still points at
  //         `data/imports/...` (phase 4 didn't finish) get renamed into
  //         `models/<slug>-vN/workflow_v<N+1>.json` and the row updated.
  //         If the rename causes a live agent set change, re-register that
  //         tenant's Inngest functions.
  //      c. Re-emit on-disk manifests that were manually deleted, using
  //         `workflow_versions.manifest_json` as the source of truth.
  //    Idempotent; safe to run every boot. Failures are logged but never
  //    block startup.
  try {
    const swept = await reconcileImports(getDb(), {
      reregister: async (tenantSlug) => {
        await reregisterInngest({ tenantSlug, scope: "tenant" });
      },
    });
    if (
      swept.expired_pruned > 0 ||
      swept.rename_completed > 0 ||
      swept.missing_file_repaired > 0 ||
      swept.failures > 0
    ) {
      console.log(
        `[bootstrap] import reconcile — pruned ${swept.expired_pruned}, repaired ${swept.rename_completed} crashed rename(s), re-emitted ${swept.missing_file_repaired} missing file(s), ${swept.failures} failure(s)`,
      );
    }
  } catch (err) {
    console.warn("[bootstrap] reconcileImports failed", err);
  }

  // 4b. Deployment-history retention. Every (re)deploy correctly tombstones
  //     the prior live row, but forced re-bootstraps + legacy churn leave the
  //     Deployments page flooded with near-identical rolled_back rows. Cap
  //     each (tenant, target, note) group to the most recent N tombstones,
  //     keeping all live/pending rows and every distinct-note history entry.
  //     Idempotent; runs every boot so the table stays bounded. Skipped under
  //     NODE_ENV=test so vitest's deployment row-count assertions don't flake.
  if (process.env.NODE_ENV !== "test") {
    try {
      const pruned = pruneRolledBackDeployments();
      if (pruned.deleted > 0) {
        console.log(
          `[bootstrap] deployment history pruned — removed ${pruned.deleted} rolled_back row(s), kept ${pruned.after} (≤${pruned.retainPerNote} per tenant/target/note)`,
        );
      }
    } catch (err) {
      console.warn("[bootstrap] pruneRolledBackDeployments failed", err);
    }
  }

  // 5. Demo-mode hydration + runner. Gated entirely by AGENTIC_DEMO_MODE
  //    (NEVER auto-enabled from NODE_ENV). Two parts:
  //      a. Seed the rich RAAS fixtures (idempotent — every helper skips
  //         rows that already exist by primary key). The seed has to run
  //         AFTER bootstrapAll so the canonical agents/agent_versions
  //         rows exist for the RAAS workflow it overlays metadata onto.
  //      b. Start the periodic event/task-resolve runner that keeps the
  //         dashboard alive with synthetic traffic. The returned `stop`
  //         is plumbed through to the Fastify onClose hook in server.ts
  //         so SIGTERM clears the intervals cleanly.
  //
  //    The demo-runner module itself also no-ops on NODE_ENV=test and
  //    when the flag is off — defense in depth so an accidental import
  //    in a future module can't spin up background traffic.
  let stopDemoRunner: () => void = () => {};
  if (isDemoMode()) {
    try {
      const seedResult = await runSeedRich({
        logger: {
          info: (msg) => console.log(msg),
          warn: (msg) => console.warn(msg),
        },
      });
      if (!seedResult.ok) {
        console.warn(
          `[bootstrap] demo seed degraded — reason=${seedResult.reason ?? "unknown"}; demo runner will still start but may have nothing to do`,
        );
      }
    } catch (err) {
      console.warn("[bootstrap] demo seed threw; continuing", err);
    }
    const runner = startDemoRunner({
      info: (msg) => console.log(msg),
      warn: (msg) => console.warn(msg),
      error: (msg) => console.error(msg),
    });
    stopDemoRunner = runner.stop;
  }

  return { inngest, functions: allFns, stopDemoRunner };
}

/**
 * Merge MCP-bridged tools (one shim per advertised MCP tool, name
 * qualified as `<server>.<tool>`) and Skills tools (`skills.list_skills`,
 * `skills.load_skill`) into the tenant's existing tools map. Native tools
 * declared in the tenant package WIN on name collisions so a tenant can
 * override an MCP shim by re-defining it locally.
 *
 * MCP failures are tolerated when the server config has `optional: true`
 * (the default in McpServerConfigSchema) — the bootstrap log captures the
 * failure but the rest of the tenant still registers. A non-optional
 * MCP failure propagates through `bootstrapAll`'s per-tenant try/catch
 * so other tenants still boot.
 */
async function expandTenantRegistry(
  slug: string,
  base: TenantRegistry | undefined,
): Promise<TenantRegistry | undefined> {
  if (!base) return base;

  // --- MCP servers -------------------------------------------------------
  const mcpConfigs = (base.mcpServers ?? []) as McpServerConfig[];
  let mcpTools: Record<string, import("@agentic/agent-kit").ToolDescriptor> = {};
  if (mcpConfigs.length > 0) {
    const mgr = getMcpManager();
    try {
      await mgr.connectAll(mcpConfigs);
      mcpTools = mgr.toolMap();
      const statuses = mgr.describe();
      const summary = statuses
        .map((s) => `${s.name}=${s.connected ? `ok(${s.toolCount})` : "fail"}`)
        .join(", ");
      console.log(`[bootstrap] mcp(${slug}): ${summary}`);
    } catch (err) {
      console.warn(`[bootstrap] mcp(${slug}): connectAll failed`, err);
    }
  }

  // --- Skills ------------------------------------------------------------
  const skillDescriptors = (base.skills ?? []) as SkillDescriptor[];
  let skillTools: Record<string, import("@agentic/agent-kit").ToolDescriptor> = {};
  if (skillDescriptors.length > 0) {
    skillTools = buildSkillTools(skillDescriptors);
    console.log(
      `[bootstrap] skills(${slug}): ${skillDescriptors.length} skill(s) — ${skillDescriptors
        .map((s) => s.name)
        .join(", ")}`,
    );
  }

  if (mcpConfigs.length === 0 && skillDescriptors.length === 0) return base;

  return {
    ...base,
    tools: {
      // MCP + Skills tools first, native tenant tools last so the tenant
      // always wins on collisions.
      ...mcpTools,
      ...skillTools,
      ...(base.tools ?? {}),
    },
  };
}
