/**
 * Boot-time wiring: runs `bootstrapAll()` from @agentic/runtime which reads
 * manifests from `models/<slug>/` and returns an array of Inngest functions,
 * then exposes them via the `inngest/fastify` adapter.
 *
 * Tenant code wiring lives HERE (not in @agentic/runtime) because pnpm's
 * isolated module resolution requires each package to declare its own deps.
 * To add a new tenant with custom tools/prompts:
 *   1. Create `tenants/<slug>/` (see tenants/raas/ as the template)
 *   2. Add `"@tenants/<slug>": "workspace:*"` to apps/api/package.json
 *   3. Import + register here
 *   4. Drop `models/<slug>/` for the manifest
 *
 * Pure-declarative tenants (manifest only, no custom code) skip steps 1-3
 * and just need a `models/<slug>/` folder — bootstrap auto-discovers them
 * and they run with the generic @agentic/tools fallbacks.
 */

import {
  bootstrapAllByTenant,
  bootstrapTenantBySlug,
  helloFn,
  inngest,
  setRuntimeGateway,
  setRuntimeMetrics,
  setMemoryDriver,
  createLocalVectorDriver,
  openaiEmbedder,
  type TenantRegistries,
} from "@agentic/runtime";
import type { Inngest, InngestFunction } from "inngest";
import raasTenant from "@tenants/raas";
import systemTenant from "@tenants/__system";
import tenantTest1 from "@tenants/tenant-test1";
import robohireTenant from "@tenants/robohire";
import northwindTenant from "@tenants/northwind";
import insightlabTenant from "@tenants/insightlab";
import zhaopinTenant from "@tenants/zhaopin";
import {
  bootstrapCodeAgents,
  setGateway as setAgentGateway,
} from "@agentic/agents";
import "@agentic/agents/system";
import type { TenantRegistry } from "@agentic/agent-kit";
import { getMcpManager, type McpServerConfig } from "@agentic/mcp";
import { buildSkillTools, type SkillDescriptor } from "@agentic/skills";
import { getLLMGateway } from "./services/llm";
import { wireLlmTelemetry } from "./services/agent-factory/llm-telemetry";
import { metrics } from "./services/metrics";
import { reconcileImports } from "./services/reconcile-imports";
import { getDb, pruneRolledBackDeployments } from "@agentic/db";
import {
  initInngestRegistry,
  reregisterInngest,
} from "./services/inngest-registry";
import { syncAllApps, startAppReconciler } from "./services/inngest-sync";
import {
  applyDemoModeOverrides,
  describeDemoMode,
  describeDemoOverrides,
  isDemoMode,
} from "./config/demo-mode.js";
import { startDemoRunner } from "./services/demo-runner.js";
import { runSeedRich } from "../scripts/seed-rich.js";

/**
 * v4 typing: TS2742 surfaces because `InngestFunction` references internal
 * `api/api` symbols. Pin the return type so consumers don't need to import
 * package internals.
 */
export interface BootstrapResult {
  inngest: Inngest.Any;
  functions: InngestFunction.Any[];
  /**
   * `stop()` for the demo-runner interval timers. No-op when
   * `AGENTIC_DEMO_MODE` is false (production) or `NODE_ENV=test`. The
   * server.ts entrypoint wires this into the graceful-shutdown drain so
   * SIGTERM cleanly clears the timers before `process.exit`.
   */
  stopDemoRunner: () => void;
}

/**
 * Map of tenant slug → tenant code registry. Keys MUST match the slug
 * derived from each `models/<folder>/` directory (e.g. "RAAS-v1" → "raas").
 *
 * Wave 4 made `definePrompt` required at boot per
 * `docs/tech-design/ar-tool.md` Option B. `__system` ships the two stub
 * prompts (`checkShape` + `applyRules`) shared by every platform
 * test-fixture workflow; without this the tests (`AGENTIC_DEV_TENANT=__system`)
 * can't boot the api.
 *
 * Stale `mi*` model directories on disk (auto-generated by the
 * manifest-import e2e suite) fail at the "tenant not seeded" check inside
 * `bootstrapTenant`, NOT at the prompt check — so they don't need an entry
 * here. `bootstrapAll`'s per-tenant try/catch keeps them from blocking boot.
 */
const TENANT_REGISTRIES: TenantRegistries = {
  raas: raasTenant,
  __system: systemTenant,
  "tenant-test1": tenantTest1,
  robohire: robohireTenant,
  northwind: northwindTenant,
  insightlab: insightlabTenant,
  zhaopin: zhaopinTenant,
};

/**
 * The MCP/Skills-expanded tenant registries, captured at boot so a runtime
 * re-register (deploy / undeploy / archive) can re-run `bootstrapAll` against
 * the SAME registries without re-connecting MCP servers. `rebuildTenantFns`
 * reads this. Empty until `bootstrapRuntime` populates it.
 */
let cachedExpanded: TenantRegistries = {};

/**
 * Re-run the manifest bootstrap and return the fresh tenant Inngest function
 * set. Called by `reregisterInngest({ scope: "tenant" })` (via dynamic import
 * to dodge the circular dep). This is what makes 上线/下线 actually hot-swap:
 *
 *   - 上线 (deploy): the import wizard renames the new manifest onto disk, then
 *     reregisters → `bootstrapAll` re-reads disk → the new agent set is served.
 *   - 下线 (disable): a route flips `agents.enabled=false`, then reregisters →
 *     `bootstrapTenant` skips disabled agents → their functions drop out.
 *   - archive: an archived tenant is skipped entirely (see runtime bootstrap).
 *
 * `bootstrapAll` is idempotent (upserts by primary key), so re-running it on a
 * live process only changes the returned function array, never the DB.
 */
export async function rebuildTenantFns(
  slug?: string,
): Promise<InngestFunction.Any[]> {
  // Scoped to one tenant app when a slug is given (the registry's common path);
  // no slug → every tenant's functions flat (back-compat for callers/tests that
  // want the whole fleet).
  if (slug) return bootstrapTenantBySlug(slug, cachedExpanded);
  return [...(await bootstrapAllByTenant(cachedExpanded)).values()].flat();
}

/**
 * Full per-tenant rebuild — every tenant's functions, grouped by slug. Used by
 * `reregisterInngest({ scope: "tenant" })` with no slug (archive/restore that
 * don't carry a slug, or a global refresh). The scoped single-slug path
 * (`rebuildTenantFns`) is preferred for deploy / 上线·下线.
 */
export async function rebuildAllTenantFnsByTenant(): Promise<
  Map<string, InngestFunction.Any[]>
> {
  return bootstrapAllByTenant(cachedExpanded);
}

/**
 * Re-run the code-agent bootstrap. Code agents are invoked synchronously
 * (`POST /v1/agents/:name/invoke`) and do NOT yet contribute Inngest functions
 * (async-via-Inngest is reserved for v2 per CLAUDE.md), so this returns an
 * empty set. Wired through so `reregisterInngest({ scope: "code_agent" })`
 * resolves a real function rather than silently no-op'ing, and so the day code
 * agents gain Inngest fns there's a single place to return them.
 */
export async function rebuildCodeAgentFns(): Promise<InngestFunction.Any[]> {
  await bootstrapCodeAgents();
  return [];
}

export async function bootstrapRuntime(): Promise<BootstrapResult> {
  // 0. Surface the demo-mode flag at the very top of the boot log so the
  //    operator can tell at a glance which mode the api is running in
  //    (production = no mock, demo = seed + loop). The architectural rule
  //    is locked: a single flag controls all "synthetic-data" behavior.
  console.log(describeDemoMode());

  // 0a. Apply demo-mode env overrides BEFORE the LLM gateway is constructed.
  //     When demo mode is ON, this swaps LLM_DEFAULT_PROVIDER → "mock" (and
  //     model → "mock-model-v1") so the demo runner's 30-sec-tick traffic
  //     never bills real LLM APIs. The on-disk `.env` is NOT touched —
  //     flipping AGENTIC_DEMO_MODE=false on the next restart restores the
  //     original values automatically. Operators can opt back into a real
  //     provider under demo mode via AGENTIC_DEMO_LLM_PROVIDER /
  //     AGENTIC_DEMO_LLM_MODEL escape hatches.
  const overrides = applyDemoModeOverrides();
  if (overrides.length > 0) {
    console.log(describeDemoOverrides(overrides));
  }

  // 1. Construct LLM gateway once and wire it into both consumers
  //    (agents package for BaseAgent.run, runtime package for step-engine logic actions).
  const gateway = getLLMGateway();
  setAgentGateway(gateway);
  setRuntimeGateway(gateway);
  // Vector-recall memory: register a real driver so ctx.memory.search() returns cosine-ranked hits
  // instead of NoMemoryDriverError. Prefer a gateway embed model when MEMORY_EMBED_MODEL is set,
  // else the self-contained local (offline, deterministic) embedder. Opt out with MEMORY_VECTOR=off.
  if (process.env.MEMORY_VECTOR !== "off") {
    const embed = openaiEmbedder() ?? undefined;
    setMemoryDriver(createLocalVectorDriver(embed ? { embed } : {}));
    // #SCALE-PGVECTOR — upgrade vector recall to Postgres/pgvector when AGENTIC_PGVECTOR_URL is set
    // (the local driver above stays as the degradation target; SQLite remains system of record).
    try {
      const { wirePgVectorMemory } = await import("./services/memory-pgvector");
      await wirePgVectorMemory();
    } catch { /* inert */ }
    console.log(`[bootstrap] memory vector driver — ${embed ? `gateway(${process.env.MEMORY_EMBED_MODEL})` : "local"} embeddings`);
  }
  // #P0-3 — persist raw LLM telemetry (model/routing/latency/size) to the llm_calls table.
  wireLlmTelemetry();
  // #SCALE-FANOUT — cross-instance SSE fanout via Redis (inert without REDIS_URL + ioredis).
  try {
    const { wireRedisFanout } = await import("./services/fanout-redis");
    void wireRedisFanout();
  } catch { /* inert */ }
  // #SCALE-RESUME — re-attach factory runs interrupted by a crash/restart (conversation checkpoint).
  try {
    const { autoResumeCrashedRuns } = await import("./services/agent-factory/run-registry");
    autoResumeCrashedRuns();
  } catch { /* best-effort */ }
  // UC-V11-22 / AR-GAP-07 — wire the prometheus metrics registry into
  // the manifest engine. Without this the registry exists but
  // `runs_total`, `run_duration_ms` stay flat for any traffic the
  // manifest engine handles (i.e. all RAAS runs).
  setRuntimeMetrics(metrics);
  console.log(
    `[bootstrap] LLM gateway online — default provider=${gateway.defaultProvider}, default model=${gateway.defaultModel ?? "(adapter default)"}, ${gateway.listProviders().length} providers registered`,
  );

  // 2. Bootstrap code-defined agents (writes agents/agent_versions/deployments rows).
  const codeSummary = await bootstrapCodeAgents();
  console.log(
    `[bootstrap] code agents ready — ${codeSummary.agentCount} registered, ${codeSummary.deploymentsWritten} new deployment(s)`,
  );

  // 3. Expand each tenant registry with MCP-bridged tools + Skills tools
  //    BEFORE handing the map to `bootstrapAll`. This keeps `@agentic/runtime`
  //    blissfully unaware of MCP/Skills — the runtime sees a single
  //    `tenantRegistry.tools` map and dispatches as usual.
  const expanded: TenantRegistries = {};
  for (const [slug, base] of Object.entries(TENANT_REGISTRIES)) {
    expanded[slug] = await expandTenantRegistry(slug, base);
  }
  // Capture for runtime re-registration (deploy / undeploy / archive). See
  // `rebuildTenantFns`.
  cachedExpanded = expanded;

  // 4. Manifest-driven (RAAS etc) Inngest functions, GROUPED BY tenant so each
  //    tenant becomes its own Inngest app (`agentic-operator-<slug>`).
  const tenantFnsByTenant = await bootstrapAllByTenant(expanded);
  const tenantFns = [...tenantFnsByTenant.values()].flat();
  const allFns = [helloFn, ...tenantFns];
  console.log(
    `[bootstrap] api serving ${allFns.length} Inngest function(s) across ${tenantFnsByTenant.size} tenant app(s) + __system (${tenantFns.length} from tenant manifests)`,
  );

  // 4a. Seed the MUTABLE per-app Inngest registry so each `/inngest[/:slug]`
  //     route serves a function set that `reregisterInngest()` can swap at
  //     runtime without a restart. The platform app (__system) carries helloFn
  //     (systemBase); code agents are sync-invoked (none yet); every tenant
  //     gets its own app entry. Before this the registry was never initialized
  //     and every re-register silently no-op'd.
  initInngestRegistry({
    systemBase: [helloFn],
    systemCodeAgent: [],
    tenants: [...tenantFnsByTenant.entries()].map(([slug, fns]) => ({
      slug,
      fns,
    })),
  });

  // 4a-bis. Register every app's serve endpoint with the Inngest dev/cloud
  //     server. The cli `-u .../inngest` auto-discovers ONLY the __system base
  //     URL; each tenant app at `/inngest/<slug>` must be PUT-synced explicitly.
  //     Best-effort + idempotent — a failed sync is logged, not fatal (the
  //     reconciler / next boot re-syncs).
  await syncAllApps({
    info: (msg) => console.log(msg),
    warn: (msg) => console.warn(msg),
  });

  // 4a-ter. Periodic reconciler: re-PUT any app the Inngest server has
  //     forgotten (e.g. the dev server restarted out from under a still-running
  //     api). Unref'd + no-op under test / when INNGEST_RECONCILE_MS=0.
  startAppReconciler({
    info: (msg) => console.log(msg),
    warn: (msg) => console.warn(msg),
  });

  // 4. Crash recovery for the manifest-import wizard (per review C1).
  //    `reconcileImports` does three things:
  //      a. Drop expired `status='pending'` rows + their staging dirs.
  //      b. Complete crashed renames: rows where `file_path` still points at
  //         `data/imports/...` (phase 4 didn't finish) get renamed into
  //         `models/<slug>-vN/workflow_v<N+1>.json` and the row updated.
  //         If the rename causes a live agent set change, re-register that
  //         tenant's Inngest functions.
  //      c. Re-emit on-disk manifests that were manually deleted, using
  //         `workflow_versions.manifest_json` as the source of truth.
  //    Idempotent; safe to run every boot. Failures are logged but never
  //    block startup.
  try {
    const swept = await reconcileImports(getDb(), {
      reregister: async (tenantSlug) => {
        await reregisterInngest({ tenantSlug, scope: "tenant" });
      },
    });
    if (
      swept.expired_pruned > 0 ||
      swept.rename_completed > 0 ||
      swept.missing_file_repaired > 0 ||
      swept.failures > 0
    ) {
      console.log(
        `[bootstrap] import reconcile — pruned ${swept.expired_pruned}, repaired ${swept.rename_completed} crashed rename(s), re-emitted ${swept.missing_file_repaired} missing file(s), ${swept.failures} failure(s)`,
      );
    }
  } catch (err) {
    console.warn("[bootstrap] reconcileImports failed", err);
  }

  // 4b. Deployment-history retention. Every (re)deploy correctly tombstones
  //     the prior live row, but forced re-bootstraps + legacy churn leave the
  //     Deployments page flooded with near-identical rolled_back rows. Cap
  //     each (tenant, target, note) group to the most recent N tombstones,
  //     keeping all live/pending rows and every distinct-note history entry.
  //     Idempotent; runs every boot so the table stays bounded. Skipped under
  //     NODE_ENV=test so vitest's deployment row-count assertions don't flake.
  if (process.env.NODE_ENV !== "test") {
    try {
      const pruned = pruneRolledBackDeployments();
      if (pruned.deleted > 0) {
        console.log(
          `[bootstrap] deployment history pruned — removed ${pruned.deleted} rolled_back row(s), kept ${pruned.after} (≤${pruned.retainPerNote} per tenant/target/note)`,
        );
      }
    } catch (err) {
      console.warn("[bootstrap] pruneRolledBackDeployments failed", err);
    }
  }

  // 5. Demo-mode hydration + runner. Gated entirely by AGENTIC_DEMO_MODE
  //    (NEVER auto-enabled from NODE_ENV). Two parts:
  //      a. Seed the rich RAAS fixtures (idempotent — every helper skips
  //         rows that already exist by primary key). The seed has to run
  //         AFTER bootstrapAll so the canonical agents/agent_versions
  //         rows exist for the RAAS workflow it overlays metadata onto.
  //      b. Start the periodic event/task-resolve runner that keeps the
  //         dashboard alive with synthetic traffic. The returned `stop`
  //         is plumbed through to the Fastify onClose hook in server.ts
  //         so SIGTERM clears the intervals cleanly.
  //
  //    The demo-runner module itself also no-ops on NODE_ENV=test and
  //    when the flag is off — defense in depth so an accidental import
  //    in a future module can't spin up background traffic.
  let stopDemoRunner: () => void = () => {};
  if (isDemoMode()) {
    try {
      const seedResult = await runSeedRich({
        logger: {
          info: (msg) => console.log(msg),
          warn: (msg) => console.warn(msg),
        },
      });
      if (!seedResult.ok) {
        console.warn(
          `[bootstrap] demo seed degraded — reason=${seedResult.reason ?? "unknown"}; demo runner will still start but may have nothing to do`,
        );
      }
    } catch (err) {
      console.warn("[bootstrap] demo seed threw; continuing", err);
    }
    const runner = startDemoRunner({
      info: (msg) => console.log(msg),
      warn: (msg) => console.warn(msg),
      error: (msg) => console.error(msg),
    });
    stopDemoRunner = runner.stop;
  }

  return { inngest, functions: allFns, stopDemoRunner };
}

/**
 * Merge MCP-bridged tools (one shim per advertised MCP tool, name
 * qualified as `<server>.<tool>`) and Skills tools (`skills.list_skills`,
 * `skills.load_skill`) into the tenant's existing tools map. Native tools
 * declared in the tenant package WIN on name collisions so a tenant can
 * override an MCP shim by re-defining it locally.
 *
 * MCP failures are tolerated when the server config has `optional: true`
 * (the default in McpServerConfigSchema) — the bootstrap log captures the
 * failure but the rest of the tenant still registers. A non-optional
 * MCP failure propagates through `bootstrapAll`'s per-tenant try/catch
 * so other tenants still boot.
 */
async function expandTenantRegistry(
  slug: string,
  base: TenantRegistry | undefined,
): Promise<TenantRegistry | undefined> {
  if (!base) return base;

  // --- MCP servers -------------------------------------------------------
  const mcpConfigs = (base.mcpServers ?? []) as McpServerConfig[];
  let mcpTools: Record<string, import("@agentic/agent-kit").ToolDescriptor> = {};
  if (mcpConfigs.length > 0) {
    const mgr = getMcpManager();
    try {
      await mgr.connectAll(mcpConfigs);
      mcpTools = mgr.toolMap();
      const statuses = mgr.describe();
      const summary = statuses
        .map((s) => `${s.name}=${s.connected ? `ok(${s.toolCount})` : "fail"}`)
        .join(", ");
      console.log(`[bootstrap] mcp(${slug}): ${summary}`);
    } catch (err) {
      console.warn(`[bootstrap] mcp(${slug}): connectAll failed`, err);
    }
  }

  // --- Skills ------------------------------------------------------------
  const skillDescriptors = (base.skills ?? []) as SkillDescriptor[];
  let skillTools: Record<string, import("@agentic/agent-kit").ToolDescriptor> = {};
  if (skillDescriptors.length > 0) {
    skillTools = buildSkillTools(skillDescriptors);
    console.log(
      `[bootstrap] skills(${slug}): ${skillDescriptors.length} skill(s) — ${skillDescriptors
        .map((s) => s.name)
        .join(", ")}`,
    );
  }

  if (mcpConfigs.length === 0 && skillDescriptors.length === 0) return base;

  return {
    ...base,
    tools: {
      // MCP + Skills tools first, native tenant tools last so the tenant
      // always wins on collisions.
      ...mcpTools,
      ...skillTools,
      ...(base.tools ?? {}),
    },
  };
}
